/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

buildscript {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    // Update to use newer kotlin plugin syntax
    kotlin("jvm") version "1.9.20"
    application
}

repositories {
    mavenCentral()
    // Add CPG's repository
    maven {
        url = uri("https://github.com/Fraunhofer-AISEC/cpg/raw/master/maven-repository")
    }
    // Add Eclipse CDT repository
    maven {
        url = uri("https://repo.eclipse.org/content/groups/releases/")
    }
    // Add Eclipse Platform repository
    maven {
        url = uri("https://download.eclipse.org/tools/cdt/releases/10.7/")
    }
    // Add additional Eclipse repositories
    maven {
        url = uri("https://download.eclipse.org/releases/2022-12/")
    }
    maven {
        url = uri("https://download.eclipse.org/tools/orbit/downloads/drops/R20221123021534/repository")
    }
}

dependencies {
    // CPG dependencies
    implementation("de.fraunhofer.aisec:cpg-core:9.0.2")
    implementation("de.fraunhofer.aisec:cpg-language-python:9.0.2")
    implementation("de.fraunhofer.aisec:cpg-analysis:9.0.2")

    // Add logging dependencies
    implementation("org.slf4j:slf4j-api:1.7.32")
    implementation("org.slf4j:slf4j-simple:1.7.32")

    testImplementation(kotlin("test"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Update mainClass to match your actual package structure
    mainClass.set("com.example.MainKt")
}

// Configure Python path
tasks.withType<JavaExec> {
    environment("PYTHONPATH", "/opt/homebrew/lib/python3.9/site-packages")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
